on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: amd64
          - os: ubuntu-24.04-arm
            platform: arm64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build
        uses: docker/build-push-action@32945a339266b759abcbdc89316275140b0fc960 # v6.8.10
        with:
          context: .
          cache-from: ghcr.io/getsentry/taskbroker:latest
          cache-to: type=inline
          platforms: linux/${{ matrix.platform }}
          tags: taskbroker:${{ matrix.platform }}
          outputs: type=docker,dest=/tmp/taskbroker-${{ matrix.platform }}.tar
          push: false

      - name: Upload Image
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: taskbroker-${{ matrix.platform }}
          path: /tmp/taskbroker-${{ matrix.platform }}.tar

  assemble-taskbroker-image:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - run: docker login --username '${{ github.actor }}' --password-stdin ghcr.io <<< "$GHCR_TOKEN"
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Download amd64 Image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.2
        with:
          name: taskbroker-amd64
          path: /tmp

      - name: Load amd64 Image
        run: docker load --input /tmp/taskbroker-amd64.tar

      - name: Download arm64 Image
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.2
        with:
          name: taskbroker-arm64
          path: /tmp

      - name: Load arm64 Image
        run: docker load --input /tmp/taskbroker-arm64.tar

      - name: Push to GitHub Container Registry
        run: |
          docker tag taskbroker:amd64 ghcr.io/getsentry/taskbroker:${{ github.sha }}-amd64
          docker push ghcr.io/getsentry/taskbroker:${{ github.sha }}-amd64

          docker tag taskbroker:arm64 ghcr.io/getsentry/taskbroker:${{ github.sha }}-arm64
          docker push ghcr.io/getsentry/taskbroker:${{ github.sha }}-arm64

          docker manifest create \
            ghcr.io/getsentry/taskbroker:${{ github.sha }} \
            --amend ghcr.io/getsentry/taskbroker:${{ github.sha }}-amd64 \
            --amend ghcr.io/getsentry/taskbroker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/getsentry/taskbroker:${{ github.sha }}

          docker manifest create \
            ghcr.io/getsentry/taskbroker:latest \
            --amend ghcr.io/getsentry/taskbroker:${{ github.sha }}-amd64 \
            --amend ghcr.io/getsentry/taskbroker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/getsentry/taskbroker:latest

          docker manifest create \
            ghcr.io/getsentry/taskbroker:nightly \
            --amend ghcr.io/getsentry/taskbroker:${{ github.sha }}-amd64 \
            --amend ghcr.io/getsentry/taskbroker:${{ github.sha }}-arm64

          docker manifest push ghcr.io/getsentry/taskbroker:nightly

  publish-taskbroker-to-dockerhub:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: [assemble-taskbroker-image]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - shell: bash
        run: |
          echo "${{ secrets.DOCKER_HUB_RW_TOKEN }}" | docker login --username=sentrybuilder --password-stdin

          # We push 3 tags to Dockerhub:
          # first, the full sha of the commit
          docker buildx imagetools create --tag getsentry/taskbroker:${GITHUB_SHA} ghcr.io/getsentry/taskbroker:${{ github.sha }}

          # second, the short sha of the commit
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          docker buildx imagetools create --tag getsentry/taskbroker:${SHORT_SHA} ghcr.io/getsentry/taskbroker:${{ github.sha }}

          # finally, nightly
          docker buildx imagetools create --tag getsentry/taskbroker:nightly ghcr.io/getsentry/taskbroker:${{ github.sha }}

  build-taskworker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - run: docker login --username '${{ github.actor }}' --password-stdin ghcr.io <<< "$GHCR_TOKEN"
      env:
        GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'

    - run: docker buildx create --driver docker-container --use

    - name: build
      run: |
        set -euxo pipefail

        if [ ${{ github.event_name }} = 'push' ]; then
          args=(
            --tag ghcr.io/getsentry/taskworker:latest
            --tag ghcr.io/getsentry/taskworker:amd64-latest
            --push
          )
        else
          args=()
        fi

        docker buildx build \
          --pull \
          --platform linux/amd64 \
          --cache-from ghcr.io/getsentry/taskworker:latest \
          --cache-to type=inline \
          --tag ghcr.io/getsentry/taskworker:${{ github.sha }} \
          "${args[@]}" \
          ./python
